from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(433, 407)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/ii.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QLabel{\n"
"color: black;\n"
"font-size: 16px;\n"
"font-family: Impact;\n"
"}\n"
"#Form{\n"
"background-image: url(:/background/background.jpg);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: silver;\n"
"}\n"
"К")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(0, 20, 331, 21))
        self.name.setObjectName("name")
        self.players = QtWidgets.QSlider(Form)
        self.players.setGeometry(QtCore.QRect(190, 70, 160, 16))
        self.players.setMinimum(2)
        self.players.setMaximum(64)
        self.players.setProperty("value", 32)
        self.players.setOrientation(QtCore.Qt.Horizontal)
        self.players.setObjectName("players")
        self.play = QtWidgets.QLabel(Form)
        self.play.setGeometry(QtCore.QRect(190, 50, 141, 20))
        self.play.setObjectName("play")
        self.port_1 = QtWidgets.QLabel(Form)
        self.port_1.setGeometry(QtCore.QRect(0, 50, 77, 14))
        self.port_1.setObjectName("port_1")
        self.name_1 = QtWidgets.QLabel(Form)
        self.name_1.setGeometry(QtCore.QRect(0, 0, 131, 16))
        self.name_1.setObjectName("name_1")
        self.password_1 = QtWidgets.QLabel(Form)
        self.password_1.setGeometry(QtCore.QRect(0, 100, 111, 16))
        self.password_1.setObjectName("password_1")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(80, 100, 115, 20))
        self.password.setObjectName("password")
        self.ad_mode = QtWidgets.QCheckBox(Form)
        self.ad_mode.setGeometry(QtCore.QRect(10, 130, 101, 18))
        self.ad_mode.setChecked(True)
        self.ad_mode.setObjectName("ad_mode")
        self.stock = QtWidgets.QCheckBox(Form)
        self.stock.setGeometry(QtCore.QRect(10, 210, 131, 18))
        self.stock.setChecked(True)
        self.stock.setObjectName("stock")
        self.all = QtWidgets.QCheckBox(Form)
        self.all.setGeometry(QtCore.QRect(10, 230, 151, 18))
        self.all.setObjectName("all")
        self.menu = QtWidgets.QCheckBox(Form)
        self.menu.setGeometry(QtCore.QRect(10, 250, 131, 18))
        self.menu.setObjectName("menu")
        self.island = QtWidgets.QComboBox(Form)
        self.island.setGeometry(QtCore.QRect(250, 100, 181, 22))
        self.island.setObjectName("island")
        self.island.addItem("")
        self.island_1 = QtWidgets.QLabel(Form)
        self.island_1.setGeometry(QtCore.QRect(200, 100, 47, 14))
        self.island_1.setObjectName("island_1")
        self.first_per = QtWidgets.QCheckBox(Form)
        self.first_per.setGeometry(QtCore.QRect(10, 270, 111, 18))
        self.first_per.setObjectName("first_per")
        self.fir_per_veh = QtWidgets.QCheckBox(Form)
        self.fir_per_veh.setGeometry(QtCore.QRect(10, 290, 195, 18))
        self.fir_per_veh.setObjectName("fir_per_veh")
        self.damage_veh = QtWidgets.QCheckBox(Form)
        self.damage_veh.setGeometry(QtCore.QRect(10, 310, 195, 18))
        self.damage_veh.setObjectName("damage_veh")
        self.player_damage = QtWidgets.QCheckBox(Form)
        self.player_damage.setGeometry(QtCore.QRect(10, 330, 141, 18))
        self.player_damage.setObjectName("player_damage")
        self.npc_damage = QtWidgets.QCheckBox(Form)
        self.npc_damage.setGeometry(QtCore.QRect(10, 350, 131, 18))
        self.npc_damage.setObjectName("npc_damage")
        self.sharks = QtWidgets.QCheckBox(Form)
        self.sharks.setGeometry(QtCore.QRect(10, 370, 97, 18))
        self.sharks.setChecked(True)
        self.sharks.setObjectName("sharks")
        self.megalodon = QtWidgets.QCheckBox(Form)
        self.megalodon.setGeometry(QtCore.QRect(10, 170, 111, 18))
        self.megalodon.setObjectName("megalodon")
        self.tp_veh = QtWidgets.QCheckBox(Form)
        self.tp_veh.setGeometry(QtCore.QRect(10, 190, 152, 18))
        self.tp_veh.setChecked(True)
        self.tp_veh.setObjectName("tp_veh")
        self.fast_travels = QtWidgets.QCheckBox(Form)
        self.fast_travels.setGeometry(QtCore.QRect(150, 130, 111, 18))
        self.fast_travels.setChecked(True)
        self.fast_travels.setObjectName("fast_travels")
        self.fuel = QtWidgets.QCheckBox(Form)
        self.fuel.setGeometry(QtCore.QRect(150, 150, 111, 18))
        self.fuel.setAcceptDrops(False)
        self.fuel.setChecked(False)
        self.fuel.setObjectName("fuel")
        self.un_comp = QtWidgets.QCheckBox(Form)
        self.un_comp.setGeometry(QtCore.QRect(10, 150, 141, 18))
        self.un_comp.setChecked(True)
        self.un_comp.setObjectName("un_comp")
        self.confirm = QtWidgets.QPushButton(Form)
        self.confirm.setGeometry(QtCore.QRect(334, 372, 131, 31))
        self.confirm.setObjectName("confirm")
        self.port = QtWidgets.QLineEdit(Form)
        self.port.setGeometry(QtCore.QRect(0, 70, 113, 20))
        self.port.setObjectName("port")
        self.starting = QtWidgets.QSlider(Form)
        self.starting.setGeometry(QtCore.QRect(260, 160, 160, 16))
        self.starting.setMinimum(10000)
        self.starting.setMaximum(250000)
        self.starting.setProperty("value", 15000)
        self.starting.setOrientation(QtCore.Qt.Horizontal)
        self.starting.setObjectName("starting")
        self.start_1 = QtWidgets.QLabel(Form)
        self.start_1.setGeometry(QtCore.QRect(260, 140, 161, 20))
        self.start_1.setObjectName("start_1")
        self.dn_l_1 = QtWidgets.QLabel(Form)
        self.dn_l_1.setGeometry(QtCore.QRect(260, 180, 201, 16))
        self.dn_l_1.setObjectName("dn_l_1")
        self.dn_l = QtWidgets.QSlider(Form)
        self.dn_l.setGeometry(QtCore.QRect(260, 200, 190, 16))
        self.dn_l.setMinimum(20)
        self.dn_l.setMaximum(120)
        self.dn_l.setProperty("value", 60)
        self.dn_l.setOrientation(QtCore.Qt.Horizontal)
        self.dn_l.setObjectName("dn_l")
        self.sunrise = QtWidgets.QDial(Form)
        self.sunrise.setGeometry(QtCore.QRect(230, 240, 50, 51))
        self.sunrise.setMaximum(100)
        self.sunrise.setProperty("value", 25)
        self.sunrise.setObjectName("sunrise")
        self.sunrise_1 = QtWidgets.QLabel(Form)
        self.sunrise_1.setGeometry(QtCore.QRect(210, 220, 91, 16))
        self.sunrise_1.setObjectName("sunrise_1")
        self.sunset_1 = QtWidgets.QLabel(Form)
        self.sunset_1.setGeometry(QtCore.QRect(340, 220, 81, 16))
        self.sunset_1.setObjectName("sunset_1")
        self.sunset = QtWidgets.QDial(Form)
        self.sunset.setGeometry(QtCore.QRect(350, 240, 50, 51))
        self.sunset.setMaximum(100)
        self.sunset.setProperty("value", 79)
        self.sunset.setObjectName("sunset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Stormworks Server Creator"))
        self.name.setText(_translate("Form", "Stormworks Server"))
        self.play.setText(_translate("Form", "Max players: 32"))
        self.port_1.setText(_translate("Form", "Port:"))
        self.name_1.setText(_translate("Form", "Server name:"))
        self.password_1.setText(_translate("Form", "Password:"))
        self.password.setText(_translate("Form", ""))
        self.ad_mode.setText(_translate("Form", "Advanced"))
        self.stock.setText(_translate("Form", "Infinity stock"))
        self.all.setText(_translate("Form", "Unlock all islands"))
        self.menu.setText(_translate("Form", "Creative menu"))
        self.island.setItemText(0, _translate("Form", "Creative island"))
        self.island_1.setText(_translate("Form", "Island:"))
        self.first_per.setText(_translate("Form", "First person"))
        self.fir_per_veh.setText(_translate("Form", "First person in vehicles"))
        self.damage_veh.setText(_translate("Form", "Vehicles damage"))
        self.player_damage.setText(_translate("Form", "Player damage"))
        self.npc_damage.setText(_translate("Form", "NPC damage"))
        self.sharks.setText(_translate("Form", "Sharks"))
        self.megalodon.setText(_translate("Form", "Megalodon"))
        self.tp_veh.setText(_translate("Form", "Teleport vehicles"))
        self.fast_travels.setText(_translate("Form", "Fast travels"))
        self.fuel.setText(_translate("Form", "Limited fuel"))
        self.un_comp.setText(_translate("Form", "Unlock compon."))
        self.confirm.setText(_translate("Form", "Confirm"))
        self.port.setText(_translate("Form", "25564"))
        self.start_1.setText(_translate("Form", "Starting currency: 15000"))
        self.dn_l_1.setText(_translate("Form", "Day and night length: 60"))
        self.sunrise_1.setText(_translate("Form", "Sunrise: 0.25"))
        self.sunset_1.setText(_translate("Form", "Sunset: 0.79"))